apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: seu_usuario_dockerhub/webapp:latest # Altere se for outro repositório
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort  # ou NodePort se for local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
